version: 2
jobs:
  build:
    working_directory: ~/npm-test
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: yarn-install
          command: yarn
      - run:
          name: test
          command: yarn test
