version: 2
machine:
  node:
    version: 6.10.3
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
test:
  override:
    - yarn test

